'use client'

import { useRouter } from 'next/navigation'

export default function GeneticPage() {
  const router = useRouter()

  return (
    <div className="min-h-screen bg-gradient-to-br from-green-950 to-teal-950 text-white pb-20">
      <header className="bg-gradient-to-r from-green-600 to-teal-600 text-white shadow-lg sticky top-0 z-10">
        <div className="px-4 py-3 flex items-center">
          <button onClick={() => router.back()} className="text-white mr-3 text-xl">←</button>
          <h1 className="text-xl font-bold">🧬 Genetic AI Optimizer</h1>
          <span className="ml-2 bg-yellow-600 text-white text-xs px-2 py-0.5 rounded-full">CONCEPT PREVIEW</span>
        </div>
      </header>

      <main className="p-4">
        <div className="bg-white text-gray-900 rounded-lg shadow p-4 mb-4">
          <p className="text-sm font-semibold">Optimization engine unavailable</p>
          <p className="text-sm mt-2">
            ROOF/OS does not currently run a validated genetic optimization model. No material,
            cost, lifespan, score, or recommended solution is generated by this screen.
          </p>
        </div>

        <div className="bg-gradient-to-br from-green-900/50 to-teal-900/50 rounded-lg p-4 border border-teal-500">
          <p className="font-semibold">🧬 Genetic optimization concept</p>
          <p className="text-xs text-teal-300 mt-1">
            A future implementation must use real inputs, a documented objective function,
            reproducible calculations, and persisted evidence before results can be used in estimating.
          </p>

          <div className="grid grid-cols-2 gap-2 mt-4 text-sm text-gray-300">
            <div className="rounded bg-green-950/70 p-3">Best score: Unknown</div>
            <div className="rounded bg-green-950/70 p-3">Material: Unknown</div>
            <div className="rounded bg-green-950/70 p-3">Cost: Unknown</div>
            <div className="rounded bg-green-950/70 p-3">Lifespan: Unknown</div>
          </div>

          <button
            type="button"
            disabled
            className="w-full mt-4 bg-gradient-to-r from-green-600 to-teal-600 text-white py-3 rounded-lg font-semibold disabled:opacity-50"
          >
            🧬 Optimization unavailable
          </button>

          <button
            onClick={() => router.push('/measure')}
            className="w-full mt-2 bg-teal-700 text-white py-3 rounded-lg font-semibold"
          >
            📐 Open Measurement
          </button>
        </div>
      </main>

      <nav className="fixed bottom-0 left-0 right-0 bg-gray-900 border-t border-teal-500 flex justify-around py-2 px-4">
        <button onClick={() => router.push('/')} className="flex flex-col items-center text-gray-400">
          <span className="text-xl">🏠</span>
          <span className="text-xs">Home</span>
        </button>
        <button onClick={() => router.push('/genetic')} className="flex flex-col items-center text-teal-500">
          <span className="text-xl">🧬</span>
          <span className="text-xs">Genetic</span>
        </button>
        <button onClick={() => router.push('/quantum')} className="flex flex-col items-center text-gray-400">
          <span className="text-xl">⚛️</span>
          <span className="text-xs">Quantum</span>
        </button>
        <button onClick={() => router.push('/ar')} className="flex flex-col items-center text-gray-400">
          <span className="text-xl">🛸</span>
          <span className="text-xs">AR</span>
        </button>
        <button onClick={() => router.push('/settings')} className="flex flex-col items-center text-gray-400">
          <span className="text-xl">⚙️</span>
          <span className="text-xs">Settings</span>
        </button>
      </nav>
    </div>
  )
}
