'use client'
import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { calculateSidingMeasurement } from '../../lib/siding/measurement'

export default function SidingPage() {
  const router=useRouter(); const [courseCount,setCourseCount]=useState(24); const [exposureInches,setExposureInches]=useState(7.25); const [widthFt,setWidthFt]=useState(32); const [wastePercent,setWastePercent]=useState(10); const [elevation,setElevation]=useState('Front'); const [inspectionId,setInspectionId]=useState(''); const [sourcePhotoId,setSourcePhotoId]=useState(''); const [saved,setSaved]=useState(false); const [error,setError]=useState('');
  const [openings,setOpenings]=useState([{id:'opening-1',widthFt:3,heightFt:7,include:true}]);
  const result=(()=>{try{return calculateSidingMeasurement({courseCount,exposureInches,widthFt,openings,wastePercent})}catch{return null}})();
  const update=(id:string,key:'widthFt'|'heightFt'|'include',value:number|boolean)=>setOpenings(openings.map(o=>o.id===id?{...o,[key]:value}:o));
  async function save(){setError('');setSaved(false);if(!result){setError('Correct the measurement inputs first.');return}const r=await fetch('/api/siding/measure',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({courseCount,exposureInches,widthFt,openings,wastePercent,elevation,inspectionId:inspectionId||undefined,sourcePhotoId:sourcePhotoId||undefined})});const d=await r.json().catch(()=>({}));if(!r.ok){setError(d.error||'Could not save measurement.');return}setSaved(true)}
  return <div className="min-h-screen bg-gray-50 pb-10"><header className="bg-gray-900 text-white sticky top-0 z-10"><div className="px-4 py-3 flex items-center"><button onClick={()=>router.back()} className="mr-3 text-xl">←</button><h1 className="text-xl font-bold">Siding Measurement</h1></div></header><main className="p-4 max-w-3xl mx-auto space-y-4">
    <section className="bg-white rounded-lg shadow p-4 border"><h2 className="font-semibold">Field-verified siding measurement</h2><p className="text-sm text-gray-600 mt-1">Rows × actual exposure = wall height. Height × width = gross area. Deduct measured openings. Apply waste last.</p></section>
    <section className="bg-white rounded-lg shadow p-4 grid grid-cols-2 gap-3"><Field label="Elevation"><input className="input" value={elevation} onChange={e=>setElevation(e.target.value)}/></Field><Field label="Course / row count"><input className="input" type="number" value={courseCount} onChange={e=>setCourseCount(Number(e.target.value))}/></Field><Field label="Actual exposure (inches)"><input className="input" type="number" step="0.01" value={exposureInches} onChange={e=>setExposureInches(Number(e.target.value))}/></Field><Field label="Wall width (feet)"><input className="input" type="number" step="0.01" value={widthFt} onChange={e=>setWidthFt(Number(e.target.value))}/></Field><Field label="Waste %"><input className="input" type="number" step="0.1" value={wastePercent} onChange={e=>setWastePercent(Number(e.target.value))}/></Field><Field label="Inspection ID (optional)"><input className="input" value={inspectionId} onChange={e=>setInspectionId(e.target.value)}/></Field><Field label="Source photo ID (optional)" wide><input className="input" value={sourcePhotoId} onChange={e=>setSourcePhotoId(e.target.value)}/></Field></section>
    <section className="bg-white rounded-lg shadow p-4"><div className="flex justify-between mb-3"><h2 className="font-semibold">Openings</h2><button className="border rounded px-3 py-1" onClick={()=>setOpenings([...openings,{id:crypto.randomUUID(),widthFt:0,heightFt:0,include:true}])}>+ Opening</button></div>{openings.map((o,i)=><div className="grid grid-cols-5 gap-2 mb-2 items-end" key={o.id}><Field label={'Width '+(i+1)}><input className="input" type="number" step="0.01" value={o.widthFt} onChange={e=>update(o.id,'widthFt',Number(e.target.value))}/></Field><Field label="Height"><input className="input" type="number" step="0.01" value={o.heightFt} onChange={e=>update(o.id,'heightFt',Number(e.target.value))}/></Field><label className="text-xs flex items-center gap-1"><input type="checkbox" checked={o.include} onChange={e=>update(o.id,'include',e.target.checked)}/> Deduct</label><span className="text-xs text-gray-500">Opening</span><button className="text-red-600 text-sm" onClick={()=>setOpenings(openings.filter(x=>x.id!==o.id))}>Remove</button></div>)}</section>
    {result&&<section className="bg-white rounded-lg shadow p-4 grid grid-cols-2 md:grid-cols-3 gap-4">{[['Calculated height',result.calculatedHeightFt.toFixed(2)+' ft'],['Gross area',result.grossAreaSqFt.toFixed(2)+' ft²'],['Opening deduction',result.openingDeductionSqFt.toFixed(2)+' ft²'],['Net area',result.netAreaSqFt.toFixed(2)+' ft²'],['Waste',result.wasteSqFt.toFixed(2)+' ft²'],['Order quantity',result.orderAreaSqFt.toFixed(2)+' ft²']].map(([l,v])=><div key={l}><p className="text-xs text-gray-500">{l}</p><p className="text-xl font-bold">{v}</p></div>)}</section>}
    {error&&<div className="bg-red-50 border border-red-300 text-red-800 p-3 rounded">{error}</div>}{saved&&<div className="bg-green-50 border border-green-300 text-green-800 p-3 rounded">Saved as unverified. It cannot be treated as approved until reviewed.</div>}<button onClick={save} className="w-full bg-gray-900 text-white py-3 rounded font-semibold">Save Field Measurement</button>
  </main></div>
}
function Field({label,children,wide=false}:{label:string,children:React.ReactNode,wide?:boolean}){return <label className={wide?'text-sm col-span-2':'text-sm'}>{label}{children}</label>}
