'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'

export default function AIPage() {
  const router = useRouter()
  const [loading, setLoading] = useState(false)
  const [report, setReport] = useState('')
  const [inspectionData, setInspectionData] = useState({
    address: '123 Main St',
    city: 'Atlanta',
    state: 'GA',
    date: '2024-01-15',
    inspector: 'Tom Wilson',
    roofCondition: 'Moderate wear with some damaged shingles',
    stormDamage: 'Yes - visible hail damage on south-facing slope',
    recommendations: 'Replace damaged shingles, inspect flashing'
  })

  const generateReport = () => {
    setLoading(true)
    // Simulate AI processing
    setTimeout(() => {
      const report = `ROOF INSPECTION REPORT

Property: ${inspectionData.address}
City: ${inspectionData.city}, ${inspectionData.state}
Date: ${inspectionData.date}
Inspector: ${inspectionData.inspector}

FINDINGS:
- ${inspectionData.roofCondition}
- Storm Damage: ${inspectionData.stormDamage}
- ${inspectionData.recommendations}

RECOMMENDATIONS:
1. Immediate: ${inspectionData.recommendations.split(',')[0]}
2. Schedule: Follow-up inspection in 30 days
3. Priority: High - due to potential water intrusion

Disclaimer: This is a preliminary report. A certified roofing professional must verify all findings.

Generated by ROOF/OS AI Assistant`
      setReport(report)
      setLoading(false)
    }, 3000)
  }

  const downloadReport = () => {
    const blob = new Blob([report], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `inspection-report-${inspectionData.address.replace(/\s/g, '')}.txt`
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <div className="min-h-screen bg-gray-50 pb-20">
      <header className="bg-blue-600 text-white shadow-lg sticky top-0 z-10">
        <div className="px-4 py-3 flex items-center">
          <button onClick={() => router.back()} className="text-white mr-3 text-xl">←</button>
          <h1 className="text-xl font-bold">🤖 AI Report Generator</h1>
        </div>
      </header>

      <main className="p-4">
        {/* Input Section */}
        <div className="bg-white rounded-lg shadow p-4 mb-4">
          <h2 className="font-semibold text-sm mb-3">📝 Inspection Details</h2>
          <div className="space-y-3">
            <input 
              type="text" 
              value={inspectionData.address}
              onChange={(e) => setInspectionData({...inspectionData, address: e.target.value})}
              className="w-full p-2 border rounded-lg text-sm"
              placeholder="Address"
            />
            <input 
              type="text" 
              value={inspectionData.roofCondition}
              onChange={(e) => setInspectionData({...inspectionData, roofCondition: e.target.value})}
              className="w-full p-2 border rounded-lg text-sm"
              placeholder="Roof Condition"
            />
            <textarea 
              value={inspectionData.recommendations}
              onChange={(e) => setInspectionData({...inspectionData, recommendations: e.target.value})}
              className="w-full p-2 border rounded-lg text-sm"
              rows={3}
              placeholder="Recommendations"
            />
          </div>
        </div>

        {/* Generate Button */}
        <button 
          onClick={generateReport}
          disabled={loading}
          className="w-full bg-blue-600 text-white py-3 rounded-lg font-semibold disabled:opacity-50 flex items-center justify-center"
        >
          {loading ? '⏳ Generating...' : '🤖 Generate AI Report'}
        </button>

        {/* Report Output */}
        {report && (
          <div className="mt-4">
            <div className="bg-white rounded-lg shadow p-4">
              <div className="flex justify-between items-center mb-3">
                <h3 className="font-semibold text-sm">📄 Generated Report</h3>
                <button 
                  onClick={downloadReport}
                  className="bg-green-600 text-white px-3 py-1 rounded text-sm"
                >
                  ⬇️ Download
                </button>
              </div>
              <pre className="whitespace-pre-wrap text-sm text-gray-700 bg-gray-50 p-3 rounded">
                {report}
              </pre>
            </div>

            {/* Approval Workflow */}
            <div className="mt-4 bg-white rounded-lg shadow p-4">
              <h3 className="font-semibold text-sm mb-3">✅ Approval Workflow</h3>
              <div className="flex space-x-2">
                <button className="flex-1 bg-green-600 text-white py-2 rounded-lg text-sm">
                  ✅ Approve
                </button>
                <button className="flex-1 bg-yellow-600 text-white py-2 rounded-lg text-sm">
                  ✏️ Edit
                </button>
                <button className="flex-1 bg-red-600 text-white py-2 rounded-lg text-sm">
                  ❌ Reject
                </button>
              </div>
              <p className="text-xs text-gray-400 mt-2">⚠️ Report must be reviewed before sending</p>
            </div>
          </div>
        )}
      </main>

      <nav className="fixed bottom-0 left-0 right-0 bg-white border-t flex justify-around py-2 px-4">
        <button onClick={() => router.push('/')} className="flex flex-col items-center text-gray-400">
          <span className="text-xl">🏠</span>
          <span className="text-xs">Home</span>
        </button>
        <button onClick={() => router.push('/leads')} className="flex flex-col items-center text-gray-400">
          <span className="text-xl">👤</span>
          <span className="text-xs">Leads</span>
        </button>
        <button onClick={() => router.push('/ai')} className="flex flex-col items-center text-blue-600">
          <span className="text-xl">🤖</span>
          <span className="text-xs">AI</span>
        </button>
        <button onClick={() => router.push('/notifications')} className="flex flex-col items-center text-gray-400">
          <span className="text-xl">🔔</span>
          <span className="text-xs">Alerts</span>
        </button>
        <button onClick={() => router.push('/settings')} className="flex flex-col items-center text-gray-400">
          <span className="text-xl">⚙️</span>
          <span className="text-xs">Settings</span>
        </button>
      </nav>
    </div>
  )
}
